### ISSUE TITLE
Error in main.py

### ISSUE THREAD

**Issue by hankbao** [wiggin15/msdn_docset#2]
Encountered an error when running main.py.

$python main.py

``` python
aa904962.aspx (0 remaining, 0 visited)
Traceback (most recent call last):
  File "main.py", line 57, in <module>
    main()
  File "main.py", line 48, in main
    crawl()
  File "main.py", line 37, in crawl
    new_urls = re.findall("(?:href|src)=['\"].*?en-us/library/windows/desktop/(\w\w\d{6}\(v=vs.85\).aspx)['\"]", cur_url_html, re.I)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/re.py", line 181, in findall
    return _compile(pattern, flags).findall(string)
TypeError: expected string or buffer
```

**Comment by wiggin15** [comment]
I updated the code to work with the current version of MSDN, so main.py should work now. It will probably break in the future again as MSDN itself changes...
